name: EDMS Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test:unit
      env:
        NODE_ENV: test
        MONGO_CONNECTION_STRING: mongodb://localhost:27017/edms-test
        SECRET_KEY: test-secret-key
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        EMAIL_USER: test@example.com
        EMAIL_PASS: test-password
    
    - name: Run integration tests
      run: npm run test:integration
      env:
        NODE_ENV: test
        MONGO_CONNECTION_STRING: mongodb://localhost:27017/edms-test
        SECRET_KEY: test-secret-key
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        EMAIL_USER: test@example.com
        EMAIL_PASS: test-password
    
    - name: Run security tests
      run: npm run test:security
      env:
        NODE_ENV: test
        MONGO_CONNECTION_STRING: mongodb://localhost:27017/edms-test
        SECRET_KEY: test-secret-key
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        EMAIL_USER: test@example.com
        EMAIL_PASS: test-password
    
    - name: Run performance tests
      run: npm run test:performance
      env:
        NODE_ENV: test
        MONGO_CONNECTION_STRING: mongodb://localhost:27017/edms-test
        SECRET_KEY: test-secret-key
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        EMAIL_USER: test@example.com
        EMAIL_PASS: test-password
    
    - name: Run CI tests
      run: npm run test:ci
      env:
        NODE_ENV: test
        MONGO_CONNECTION_STRING: mongodb://localhost:27017/edms-test
        SECRET_KEY: test-secret-key
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        EMAIL_USER: test@example.com
        EMAIL_PASS: test-password
    
    - name: Generate test coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
